### ISSUE TITLE
Is this framework effectively a wrapper around the editor?

### ISSUE THREAD

**Issue by zeplar-exe** [JustDooooIt/GMUI#1]
Just found this and it's actually something I've been looking for. However, it seems like it's moreso a  replacement for the editor than a UI framework. It doesn't seem like pages can be implemented inside of scenes, but rather _are_ full scenes themselves. This limits the effectiveness of MVVM because the UI is forced to be defined with the rest of the scene (in the case of a HUD, for example).

Did I miss something, or is this design limitation intentional?

**Comment by JustDooooIt** [comment]
GMUI is not a wrapper for the editor. In fact, the .gmui file will be converted into a Godot scene file and a gdscript file bound to it before each run. Therefore, it should be possible to use GMUI in your scenes if you want to. The relevant converted products are in the addons/gmui/dist directory, which you can handle yourself.

**Comment by JustDooooIt** [comment]
GMUI is not a wrapper for the editor. In fact, the .gmui file will be converted into a Godot scene file and a gdscript file bound to it before each run. Therefore, it should be possible to use GMUI in your scenes if you want to. The relevant converted products are in the addons/gmui/dist directory, which you can handle yourself.

**Comment by zeplar-exe** [comment]
@JustDooooIt 

What I mean by wrapper is that the workflow is constrained to the framework instead of the editor wherever you want to use it for UI. Apologies if I wasn't clear.

In that case though, it's not made clear that the plugin generates scenes. ~~Even then, you have to regenerate the scene whenever you edit the UI, no? Would this save your changes at all? (can't test these at the moment)~~ Nevermind that, I see what you mean. This behavior should be outlined in the Readme, though.
