### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by clemens-tolboom** [JustDooooIt/GMUI#3]
Got notified by GitHub on my **For you** .. interesting add-on!

## README

- does not have explanation for the README title "Godot MVVM UI" ... what is a MVVM? Guess it would help to tell people.
- version 1.0.0 is out ... does that mean it's completed regarding https://github.com/JustDooooIt/GMUI#roadmap Bidirectional binding?

## Files

- [export_presets.cfg](https://github.com/JustDooooIt/GMUI/blob/master/export_presets.cfg) should not be in git?
- .gitattributes should ignore most directories. Below is the root content of the downloaded ZIP file:

```zsh
tree -L 1
.
├── LICENSE
├── README.ZH.md
├── README.md
├── addons
├── components
├── docs
├── examples
├── export_presets.cfg
├── gmui.json
├── pages
├── project.godot
├── scripts
└── textures
```

## Builder or Runtime

> Your page will be built as a scene in `addons/gmui/dist/scenes/pages/{page_name}.tscn`.

Is the add-on still needed after a build?

(I now go testing)

**Comment by moluopro** [comment]
First, what is MVVM may require you to google to understand it yourself. Or you can think of GMUI as a better UI framework, you don't need to care so much about the concept.

Secondly, version 1.0 means the main function is finished. But all the tags are reused Godot's nodes, for the time being, there is no official component library to provide a good look.

Third, if you want to use this plugin, you can search for GMUI directly in the asset
 store in Godot editor and install it with one click. Or you can download the zip archive and then import the plugin manually. Either way, remember to check the box to enable the plugin after you finish the installation.

Fourth, you don't need to care about what happens after the project is built, unless you need to make changes to the framework. Once you have imported the plugin and enabled it, you can simply run the project. After each modification to your Godot project, you only need to click run project.

**Comment by moluopro** [comment]
Also, the root directory of repository is actually a Godot example project, so there will be some files in there that have nothing to do with GMUI.

**Comment by MoLuoPro** [comment]
As you can see, the features checked in the roadmap are already done, such as two-way binding. We are still considering whether MVVM needs to be explained in the documentation. If you are interested, you can also help to modify the readme file

**Comment by moluopro** [comment]
As you can see, the features checked in the roadmap are already done, such as bidirectional binding. We are still considering whether MVVM needs to be explained in the documentation. If you are interested, you can also help to modify the readme file.

**Comment by clemens-tolboom** [comment]
> First, what is MVVM may require you to google to understand it yourself. Or you can think of GMUI as a better UI framework, you don't need to care so much about the concept.

That is exactly my point ... why google for MVVM ... remove it from the title and make it to the point "UI builder", "Form builder"

> 
> Secondly, version 1.0 means the main function is finished. But all the tags are reused Godot's nodes, for the time being, there is no official component library to provide a good look.

Not sure I get this. Next comment suggest bidirectional is finished 👍 
> 
> Third, if you want to use this plugin, you can search for GMUI directly in the asset store in Godot editor and install it with one click. Or you can download the zip archive and then import the plugin manually. Either way, remember to check the box to enable the plugin after you finish the installation.

The ZIP contains too much.

Please check https://docs.godotengine.org/en/stable/community/asset_library/submitting_to_assetlib.html#recommendations

### .gitattributes
```
# Normalize line endings for all files that Git considers text files.
* text=auto eol=lf

# Only include the addons folder when downloading from the Asset Library.
/**        export-ignore
/addons    !export-ignore
/addons/** !export-ignore
```

> Fourth, you don't need to care about what happens after the project is built, unless you need to make changes to the framework. Once you have imported the plugin and enabled it, you can simply run the project. After each modification to your Godot project, you only need to click run project.

No docs means no way of writing a PR ... but that is about contributing.

**Comment by moluopro** [comment]
Thank you for your suggestions. Also, we don't have a good idea yet about removing the MVVM wording. As for my fourth point above, the intent was to tell you that the build product under addons is not something the average user needs to care about. If you want to know the details, it's actually written clearly in the readme :  

<img width="526" alt="20230626124200" src="https://github.com/JustDooooIt/GMUI/assets/55039286/191df61e-7767-4cf1-958d-31820b0f1d91">
