### ISSUE TITLE
[BUG] Installing from AssetLib doesnt work

### ISSUE THREAD

**Issue by 3ddelano** [JustDooooIt/GMUI#4]
After installing the plugin from the AssetLib in Godot 4.0.3. It doesnt show in ProjectSettings->Plugins. This is because the `addons/` folder is not present when downloading from AssetLib as shown in the image below.

Solution: Wrap the `gmui` folder in an `addons` folder.

![image](https://github.com/JustDooooIt/GMUI/assets/24526102/2142edac-6729-4eae-b8ff-01631566fa75)

**Comment by moluopro** [comment]
I checked the plugin packages available on Github and Godot AssetLib and neither of them found the problem you mentioned. Can you try again? Are you using the latest version of GMUI?

**Comment by 3ddelano** [comment]
The screenshot above was taken a couple of hours ago from the Godot 4.0.3 editor.

Steps to reproduce
1. Open Godot 4.0.3
2. Goto AssetLib
3. Search for GMUI and click the first result, then after it has downloaded, click Install.
4. In the popup, that shows the files of the add-on. The addons folder is missing. And on clicking install the addon is installed to `res://` instead of `res://addons`

Possible reason: Perhaps the plugin version submitted to Godot asset library is not updated.

**Comment by moluopro** [comment]
I downloaded the plugin package from Github, the AssetLib web page, and the editor's built-in AssetLib page separately, and only the one downloaded in the editor is problematic. But by definition, the plug-in package downloaded from the AssetLib web page and the editor page should be the same. I'm not sure why this is the case for now.

**Comment by moluopro** [comment]
Already solved it. Addons directory is fine, but you have to wrap the whole addons directory in a folder, otherwise the editor page will have problems with automatic download. Strangely enough, everything works fine with the manual import of the addons. This should be a bug or unreasonable design of Godot. For now I can only package AssetLib separately to solve this problem.
